### PR TITLE
Radovan Bast

### PR DESCRIPTION
**Pull request by pweschmidt**
Episode 28 with Radovan Bast.

### CODE REVIEW

**Comment by vsoch** [comment]
Lovely! I'll get in a listen today :)

**Comment by vsoch** [comment]
hey @pweschmidt ! So my one general comment is that this episode is really way too long - I think early on we talked about having 20 minute episodes, 25 would be considered long (but still okay) and 30something would only be appropriate for perhaps two people. We are too close to release to change this now, but for the future I'd like to ask you to please be selective about the content you include so that the episode is closer to 20 minutes. To give you a sense of my times, I typically record 50 minutes and cut it down to 20-25ish. It's hard to not want to include everything, but if you take a few rounds of listening for edits, you'll see that there are parts that don't contribute greatly to the flow of conversation (and maybe the listener would even get bored). Let me know your thoughts, and if you are still in agreement about the 20 minute length that we have traditionally done, and I've set as an expectation for the show.

**Comment by pweschmidt** [comment]
Hi Vanessa
thank you again for pushing the new episode live today and for your continuing efforts and support.
I guess this episode isn't the most thrilling I have submitted so far. But I must confess I was a bit taken aback by the tone of your message in which I sensed some frustration. 
I will need a bit of time to gather my thoughts and will respond to the points you made in a separate email. I hope this doesn't stop the going live today, though. Best wishes, Peter

**Comment by vsoch** [comment]
Sorry I didn’t mean to have a tone! Just to bring up that the episode was a little long. How could I say it better next time?

**Comment by vsoch** [comment]
And of course it’s still going live, I enjoyed the episode a lot! It was just a little long, and It’s important we are on the same page about that :)

**Pull request merged**
